language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add greenkeeper-lockfile
  - yarn install
install: yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn run build
deploy:
  provider: pages:git
  fqdn: v2.teamif.io
  local_dir: build
  edge: true
  token:
    secure: hZFVqAtPVY14nBtRKZUT0mW1Z2roQyZtla4LDTVd3MpLRQDrbTr0AxEoNfTRhsTZOsuiQc0gtsuArjrY8T3l1n5XuxNp8R+GsedLVfaP9/m3TURG2kvLt3/koe6O52iy4y3+5OVkj/wmt1ha+KP6ETDtcj9fpsrlQqg51DdNT+gmWOAdVsUXEo95BsTJsSwdsFudiIFlkzkFOXgzW9HZ91lFpqo2yVqb+5lKAZkjyHaURZzfgCICdydDeCR3OoTZ63QrRpe+FThUqXItZE0+TEzAVdRn4iDByScGg2O132FpMfU2yvmHkWNEmWjpWx/G4UsAj/g9i5Ci4xz1fuj8eJMHCb90txxO1I5946xTeuAhMyEoUxG8YQ5d96a3Y6gOf8Q+PJUeup5LRShb7dSjB57IeY4m7GRVipYGMs+rhJ/lYggMdaGUF7A00Q+RTjSD6eSEoOICD+TYGCOu5w/q/nI/JUId/1xxnqMhlwWsWtdoUE+IL8uNRuvjwvQwaDIpLoIcsRe82UGC72uZ+zPNzpoBSZGcT9lo1iNYEBPbwjQKev42UzeM3PkenVxEes7S1d8r5dOtp0+Oocc4Kpm5uoeLID83ndQivCKsuA0hPtWjcr6/rG3kBddhaZdCrEqIMnfheCFId3WMY136TJHv7rPbSjaX62R04NePsf7l3QE=
