trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
      displayName: Install Node.js
    - task: CmdLine@2
      displayName: npm install and build
      inputs:
        script: >
          npm install

          npm run build
    - task: CmdLine@2
      displayName: Deploy
      inputs:
        script: >
          git config --local user.name $(username)

          git config --local user.email $(useremail)

          npm install gh-pages

          echo $(cname) >> build/CNAME

          npx gh-pages -r https://$(Token)@github.com/Team-IF/TeamIF-Site-v2.git -d build